[[emoji]]
match = "(?i:(^â˜ ï¸)|(Bandwidth)|(expire)|(æµé‡)|(æ—¶é—´)|(åº”æ€¥)|(è¿‡æœŸ))"
emoji = "â˜ ï¸"

[[emoji]]
match = "((^ğŸ¶)|(NetEaseMusic)|(ç½‘æ˜“äº‘éŸ³ä¹)|(ç½‘æ˜“äº‘è§£é”))"
emoji = "ğŸ¶"

[[emoji]]
match = "((^ğŸ‡¦ğŸ‡±)|(\\bAL(?:[-_\\s]?\\d+|_)?\\b)|(é˜¿å°”å·´å°¼äºš)|(Albania))"
emoji = "ğŸ‡¦ğŸ‡±"

[[emoji]]
match = "((^ğŸ‡´ğŸ‡²)|(\\bOM(?:[-_\\s]?\\d+|_)?\\b)|(é˜¿æ›¼è‹ä¸¹)|(é©¬æ–¯å–€ç‰¹)|(Muscat))"
emoji = "ğŸ‡´ğŸ‡²"

[[emoji]]
match = "((^ğŸ‡¦ğŸ‡¿)|(\\bAZ(?:[-_\\s]?\\d+|_)?\\b)|(é˜¿å¡æ‹œç–†)|(Azerbaijan))"
emoji = "ğŸ‡¦ğŸ‡¿"

[[emoji]]
match = "((^ğŸ‡ªğŸ‡¬)|(\\bEG(?:[-_\\s]?\\d+|_)?\\b)|(åŸƒåŠ)|(Egypt))"
emoji = "ğŸ‡ªğŸ‡¬"

[[emoji]]
match = "((^ğŸ‡ªğŸ‡ª)|(\\bEE(?:[-_\\s]?\\d+|_)?\\b)|(çˆ±æ²™å°¼äºš)|(Estonia))"
emoji = "ğŸ‡ªğŸ‡ª"

[[emoji]]
match = "((^ğŸ‡§ğŸ‡­)|(\\bBH(?:[-_\\s]?\\d+|_)?\\b)|(å·´æ—)|(Bahrain))"
emoji = "ğŸ‡§ğŸ‡­"

[[emoji]]
match = "((^ğŸ‡§ğŸ‡¹)|(\\bBT(?:[-_\\s]?\\d+|_)?\\b)|(ä¸ä¸¹)|(Bhutan))"
emoji = "ğŸ‡§ğŸ‡¹"

[[emoji]]
match = "((^ğŸ‡¨ğŸ‡«)|(ä¸­éå…±å’Œå›½)|(Central African Republic))"
emoji = "ğŸ‡¨ğŸ‡«"

[[emoji]]
match = "((^ğŸ‡µğŸ‡¦)|(\\bPA(?:[-_\\s]?\\d+|_)?\\b)|(å·´æ‹¿é©¬)|(Panama))"
emoji = "ğŸ‡µğŸ‡¦"

[[emoji]]
match = "((^ğŸ‡§ğŸ‡¬)|(\\bBG(?!P)(?:[-_\\s]?\\d+|_)?\\b)|(ä¿åŠ åˆ©äºš)|(Bulgaria))"
emoji = "ğŸ‡§ğŸ‡¬"

[[emoji]]
match = "((^ğŸ‡²ğŸ‡°)|(\\bMK(?:[-_\\s]?\\d+|_)?\\b)|(åŒ—é©¬å…¶é¡¿)|(Macedonia))"
emoji = "ğŸ‡²ğŸ‡°"

[[emoji]]
match = "((^ğŸ‡§ğŸ‡¦)|(\\bBA(?:[-_\\s]?\\d+|_)?\\b)|(æ³¢é»‘å…±å’Œå›½)|(æ³¢å£«å°¼äºšä¸èµ«å¡å“¥ç»´çº³)|(Bosnia)|(Herzegovina))"
emoji = "ğŸ‡§ğŸ‡¦"

[[emoji]]
match = "((^ğŸ‡»ğŸ‡¦)|(\\bVA(?:[-_\\s]?\\d+|_)?\\b)|(æ¢µè’‚å†ˆ)|(Vatican))"
emoji = "ğŸ‡»ğŸ‡¦"

[[emoji]]
match = "((^ğŸ‡¬ğŸ‡ª)|(\\bGE(?:[-_\\s]?\\d+|_)?\\b)|(æ ¼é²å‰äºš)|(Georgia))"
emoji = "ğŸ‡¬ğŸ‡ª"

[[emoji]]
match = "((^ğŸ‡°ğŸ‡¿)|(\\bKZ(?:[-_\\s]?\\d+|_)?\\b)|(å“ˆè¨å…‹æ–¯å¦)|(Kazakhstan))"
emoji = "ğŸ‡°ğŸ‡¿"

[[emoji]]
match = "((^ğŸ‡°ğŸ‡¬)|(\\bKG(?:[-_\\s]?\\d+|_)?\\b)|(å‰å°”å‰æ–¯æ–¯å¦)|(Kyrgyzstan))"
emoji = "ğŸ‡°ğŸ‡¬"

[[emoji]]
match = "((^ğŸ‡°ğŸ‡­)|(\\bKH(?:[-_\\s]?\\d+|_)?\\b)|(æŸ¬åŸ”å¯¨)|(Cambodia))"
emoji = "ğŸ‡°ğŸ‡­"

[[emoji]]
match = "((^ğŸ‡­ğŸ‡·)|(\\bHR(?:[-_\\s]?\\d+|_)?\\b)|(å…‹ç½—åœ°äºš)|(Croatia))"
emoji = "ğŸ‡­ğŸ‡·"

[[emoji]]
match = "((^ğŸ‡°ğŸ‡ª)|(\\bKE(?:[-_\\s]?\\d+|_)?\\b)|(è‚¯å°¼äºš)|(Kenya))"
emoji = "ğŸ‡°ğŸ‡ª"

[[emoji]]
match = "((^ğŸ‡±ğŸ‡¦)|(\\bLA(?:[-_\\s]?\\d+|_)?\\b)|(è€æŒ)|(Vientiane)|(Laos))"
emoji = "ğŸ‡±ğŸ‡¦"

[[emoji]]
match = "((^ğŸ‡±ğŸ‡»)|(\\bLV(?:[-_\\s]?\\d+|_)?\\b)|(æ‹‰è„±ç»´äºš)|(Latvia))"
emoji = "ğŸ‡±ğŸ‡»"

[[emoji]]
match = "((^ğŸ‡±ğŸ‡¹)|(\\bLT(?!D)(?:[-_\\s]?\\d+|_)?\\b)|(ç«‹é™¶å®›)|(Lietuvos))"
emoji = "ğŸ‡±ğŸ‡¹"

[[emoji]]
match = "((^ğŸ‡±ğŸ‡º)|(\\bLU(?:[-_\\s]?\\d+|_)?\\b)|(å¢æ£®å ¡)|(Luxemburg)|(Luxembourg))"
emoji = "ğŸ‡±ğŸ‡º"

[[emoji]]
match = "((^ğŸ‡²ğŸ‡³)|(\\bMN(?:[-_\\s]?\\d+|_)?\\b)|(è’™å¤)|(ĞœĞ¾Ğ½Ğ³Ğ¾Ğ»ÑƒĞ»Ñ)|(Mongolia))"
emoji = "ğŸ‡²ğŸ‡³"

[[emoji]]
match = "((^ğŸ‡µğŸ‡ª)|(\\bPE(?:[-_\\s]?\\d+|_)?\\b)|(ç§˜é²)|(Peru))"
emoji = "ğŸ‡µğŸ‡ª"

[[emoji]]
match = "((^ğŸ‡²ğŸ‡²)|(\\bMM(?:[-_\\s]?\\d+|_)?\\b)|(ç¼…ç”¸)|(Myanmar))"
emoji = "ğŸ‡²ğŸ‡²"

[[emoji]]
match = "((^ğŸ‡²ğŸ‡½)|(\\bMX(?:[-_\\s]?\\d+|_)?\\b)|(å¢¨è¥¿å“¥)|(Mexico))"
emoji = "ğŸ‡²ğŸ‡½"

[[emoji]]
match = "((^ğŸ‡¦ğŸ‡¶)|(\\bAQ(?:[-_\\s]?\\d+|_)?\\b)|(å—æ)|(Antarctica))"
emoji = "ğŸ‡¦ğŸ‡¶"

[[emoji]]
match = "((^ğŸ‡³ğŸ‡¬)|(\\bNG(?:[-_\\s]?\\d+|_)?\\b)|(å°¼æ—¥åˆ©äºš)|(Nigeria))"
emoji = "ğŸ‡³ğŸ‡¬"

[[emoji]]
match = "((^ğŸ‡µğŸ‡¹)|(\\bPT(?:[-_\\s]?\\d+|_)?\\b)|(è‘¡è„ç‰™)|(Portugal))"
emoji = "ğŸ‡µğŸ‡¹"

[[emoji]]
match = "((^ğŸ‡¶ğŸ‡¦)|(\\bQA(?:[-_\\s]?\\d+|_)?\\b)|(å¡å¡”å°”)|(Qatar))"
emoji = "ğŸ‡¶ğŸ‡¦"

[[emoji]]
match = "((^ğŸ‡·ğŸ‡¸)|(\\bRS(?:[-_\\s]?\\d+|_)?\\b)|(å¡å°”ç»´äºš)|(Serbia))"
emoji = "ğŸ‡·ğŸ‡¸"

[[emoji]]
match = "((^ğŸ‡¨ğŸ‡¾)|(\\bCY(?:[-_\\s]?\\d+|_)?\\b)|(å¡æµ¦è·¯æ–¯)|(Cyprus))"
emoji = "ğŸ‡¨ğŸ‡¾"

[[emoji]]
match = "((^ğŸ‡¸ğŸ‡°)|(\\bSK(?:[-_\\s]?\\d+|_)?\\b)|(æ–¯æ´›ä¼å…‹)|(Slovensko))"
emoji = "ğŸ‡¸ğŸ‡°"

[[emoji]]
match = "((^ğŸ‡¸ğŸ‡®)|(\\bSI(?:[-_\\s]?\\d+|_)?\\b)|(æ–¯æ´›æ–‡å°¼äºš)|(Slovenia))"
emoji = "ğŸ‡¸ğŸ‡®"

[[emoji]]
match = "((^ğŸ‡¹ğŸ‡¬)|(\\bTG(?:[-_\\s]?\\d+|_)?\\b)|(å¤šå“¥)|(Togo))"
emoji = "ğŸ‡¹ğŸ‡¬"

[[emoji]]
match = "((^ğŸ‡¹ğŸ‡³)|(\\bTN(?:[-_\\s]?\\d+|_)?\\b)|(çªå°¼æ–¯)|(Tunisia))"
emoji = "ğŸ‡¹ğŸ‡³"

[[emoji]]
match = "((^ğŸ‡ºğŸ‡¾)|(\\bUY(?:[-_\\s]?\\d+|_)?\\b)|(ä¹Œæ‹‰åœ­)|(Uruguay))"
emoji = "ğŸ‡ºğŸ‡¾"

[[emoji]]
match = "((^ğŸ‡¬ğŸ‡·)|(\\bGR(?:[-_\\s]?\\d+|_)?\\b)|(å¸Œè…Š)|(Greece))"
emoji = "ğŸ‡¬ğŸ‡·"

[[emoji]]
match = "((^ğŸ‡³ğŸ‡¿)|(\\bNZ(?:[-_\\s]?\\d+|_)?\\b)|(æ–°è¥¿å…°)|(çº½è¥¿å…°)|(New Zealand))"
emoji = "ğŸ‡³ğŸ‡¿"

[[emoji]]
match = "((^ğŸ‡®ğŸ‡·)|(\\bIR(?:[-_\\s]?\\d+|_)?\\b)|(ä¼Šæœ—)|(Iran))"
emoji = "ğŸ‡®ğŸ‡·"

[[emoji]]
match = "((^ğŸ‡¯ğŸ‡´)|(\\bJO(?:[-_\\s]?\\d+|_)?\\b)|(çº¦æ—¦)|(Jordan))"
emoji = "ğŸ‡¯ğŸ‡´"

[[emoji]]
match = "((^ğŸ‡¨ğŸ‡±)|(\\bCL(?:[-_\\s]?\\d+|_)?\\b)|(æ™ºåˆ©)|(æ™ºåŠ›)|(Chile))"
emoji = "ğŸ‡¨ğŸ‡±"

[[emoji]]
match = "((^ğŸ‡¦ğŸ‡¨)|(\\bAC(?:[-_\\s]?\\d+|_)?\\b)|(Ascension)|(é˜¿æ£®æ¾))"
emoji = "ğŸ‡¦ğŸ‡¨"

[[emoji]]
match = "((^ğŸ‡¦ğŸ‡¹)|(\\bAT(?:[-_\\s]?\\d+|_)?\\b)|(Austria)|(Vienna)|(å¥¥åœ°åˆ©)|(ç»´ä¹Ÿçº³))"
emoji = "ğŸ‡¦ğŸ‡¹"

[[emoji]]
match = "((^ğŸ‡§ğŸ‡©)|(\\bBD(?:[-_\\s]?\\d+|_)?\\b)|(Bengal)|(Bangladesh)|(å­ŸåŠ æ‹‰))"
emoji = "ğŸ‡§ğŸ‡©"

[[emoji]]
match = "((^ğŸ‡¨ğŸ‡´)|(\\bCO(?!G|L)(?:[-_\\s]?\\d+|_)?\\b)|(Colombia)|(å“¥ä¼¦æ¯”äºš))"
emoji = "ğŸ‡¨ğŸ‡´"

[[emoji]]
match = "((^ğŸ‡¨ğŸ‡·)|(\\bCR(?:[-_\\s]?\\d+|_)?\\b)|(Costa Rica)|(å“¥æ–¯è¾¾é»åŠ ))"
emoji = "ğŸ‡¨ğŸ‡·"

[[emoji]]
match = "((^ğŸ‡¨ğŸ‡¿)|(\\bCZ(?:[-_\\s]?\\d+|_)?\\b)|(Czech)|(æ·å…‹))"
emoji = "ğŸ‡¨ğŸ‡¿"

[[emoji]]
match = "((^ğŸ‡ªğŸ‡¨)|(\\bEC(?:[-_\\s]?\\d+|_)?\\b)|(Ecuador)|(å„ç“œå¤šå°”))"
emoji = "ğŸ‡ªğŸ‡¨"

[[emoji]]
match = "((^ğŸ‡«ğŸ‡®)|(\\bFI(?:[-_\\s]?\\d+|_)?\\b)|(Finland)|(Helsinki)|(èŠ¬å…°)|(èµ«å°”è¾›åŸº))"
emoji = "ğŸ‡«ğŸ‡®"

[[emoji]]
match = "((^ğŸ‡­ğŸ‡º)|(\\bHU(?:[-_\\s]?\\d+|_)?\\b)|(Hungary)|(åŒˆç‰™åˆ©))"
emoji = "ğŸ‡­ğŸ‡º"

[[emoji]]
match = "((^ğŸ‡®ğŸ‡²)|(\\bIM(?:[-_\\s]?\\d+|_)?\\b)|(IMAN)|(é©¬æ©å²›)|(Mann))"
emoji = "ğŸ‡®ğŸ‡²"

[[emoji]]
match = "((^ğŸ‡®ğŸ‡©)|(\\bID(?:[-_\\s]?\\d+|_)?(?!C)\\b)|(Indonesia)|(Jakarta)|(å°å°¼)|(å°åº¦å°¼è¥¿äºš)|(é›…åŠ è¾¾))"
emoji = "ğŸ‡®ğŸ‡©"

[[emoji]]
match = "((^ğŸ‡®ğŸ‡ª)|(\\bIE(?:[-_\\s]?\\d+|_)?\\b)|(Ireland)|(Dublin)|(çˆ±å°”å…°)|(éƒ½æŸæ—))"
emoji = "ğŸ‡®ğŸ‡ª"

[[emoji]]
match = "((^ğŸ‡®ğŸ‡±)|(\\bIL(?:[-_\\s]?\\d+|_)?\\b)|(Israel)|(ä»¥è‰²åˆ—))"
emoji = "ğŸ‡®ğŸ‡±"

[[emoji]]
match = "((^ğŸ‡®ğŸ‡¶)|(\\bIQ(?:[-_\\s]?\\d+|_)?\\b)|(Iraq)|(ä¼Šæ‹‰å…‹))"
emoji = "ğŸ‡®ğŸ‡¶"

[[emoji]]
match = "((^ğŸ‡®ğŸ‡¹)|(\\bIT(?:[-_\\s]?\\d+|_)?\\b)|(Italy)|(Milan)|(æ„å¤§åˆ©)|(ç±³å…°))"
emoji = "ğŸ‡®ğŸ‡¹"

[[emoji]]
match = "((^ğŸ‡²ğŸ‡©)|(\\bMD(?:[-_\\s]?\\d+|_)?\\b)|(Moldova)|(æ‘©å°”å¤šç“¦))"
emoji = "ğŸ‡²ğŸ‡©"

[[emoji]]
match = "((^ğŸ‡²ğŸ‡¦)|(\\bMA(?:[-_\\s]?\\d+|_)?\\b)|(Morocco)|(æ‘©æ´›å“¥))"
emoji = "ğŸ‡²ğŸ‡¦"

[[emoji]]
match = "((^ğŸ‡³ğŸ‡µ)|(\\bNP(?:[-_\\s]?\\d+|_)?\\b)|(Nepal)|(å°¼æ³Šå°”))"
emoji = "ğŸ‡³ğŸ‡µ"

[[emoji]]
match = "((^ğŸ‡³ğŸ‡´)|(\\bNO(?:[-_\\s]?\\d+|_)?\\b)|(Norway)|(æŒªå¨))"
emoji = "ğŸ‡³ğŸ‡´"

[[emoji]]
match = "((^ğŸ‡µğŸ‡°)|(\\bPK(?:[-_\\s]?\\d+|_)?\\b)|(Pakistan)|(å·´åŸºæ–¯å¦))"
emoji = "ğŸ‡µğŸ‡°"

[[emoji]]
match = "((^ğŸ‡µğŸ‡·)|(\\bPR(?:[-_\\s]?\\d+|_)?\\b)|(Puerto.*?Rico)|(æ³¢å¤šé»å„))"
emoji = "ğŸ‡µğŸ‡·"

[[emoji]]
match = "((^ğŸ‡¨ğŸ‡­)|(\\bCH(?:[-_\\s]?\\d+|_)?\\b)|(Switzerland)|(Zurich)|(ç‘å£«)|(è‹é»ä¸–)|(æ—¥å†…ç“¦))"
emoji = "ğŸ‡¨ğŸ‡­"

[[emoji]]
match = "((^ğŸ‡»ğŸ‡ª)|(\\bVE(?:[-_\\s]?\\d+|_)?\\b)|(Venezuela)|(å§”å†…ç‘æ‹‰))"
emoji = "ğŸ‡»ğŸ‡ª"

[[emoji]]
match = "((^ğŸ‡¦ğŸ‡·)|(\\bAR(?:[-_\\s]?\\d+|_)?\\b)|(é˜¿æ ¹å»·)|(Argentina))"
emoji = "ğŸ‡¦ğŸ‡·"

[[emoji]]
match = "((^ğŸ‡§ğŸ‡ª)|(\\bBE(?:[-_\\s]?\\d+|_)?\\b)|(Belgium)|(æ¯”åˆ©æ—¶))"
emoji = "ğŸ‡§ğŸ‡ª"

[[emoji]]
match = "((^ğŸ‡§ğŸ‡·)|(\\bBR(?:[-_\\s]?\\d+|_)?\\b)|(Brazil)|(Paulo)|(å·´è¥¿)|(åœ£ä¿ç½—))"
emoji = "ğŸ‡§ğŸ‡·"

[[emoji]]
match = "((^ğŸ‡²ğŸ‡¾)|(\\bMY(?:[-_\\s]?\\d+|_)?\\b)|(Malaysia)|(é©¬æ¥è¥¿äºš)|(é©¬æ¥))"
emoji = "ğŸ‡²ğŸ‡¾"

[[emoji]]
match = "((^ğŸ‡·ğŸ‡´)|(\\bRO(?:[-_\\s]?\\d+|_)?\\b)|(Romania)|(ç½—é©¬å°¼äºš))"
emoji = "ğŸ‡·ğŸ‡´"

[[emoji]]
match = "((^ğŸ‡¸ğŸ‡¦)|(\\bSA(?:[-_\\s]?\\d+|_)?\\b)|(Arabia)|(æ²™ç‰¹))"
emoji = "ğŸ‡¸ğŸ‡¦"

[[emoji]]
match = "((^ğŸ‡¸ğŸ‡ª)|(\\bSE(?:[-_\\s]?\\d+|_)?\\b)|(Sweden)|(ç‘å…¸))"
emoji = "ğŸ‡¸ğŸ‡ª"

[[emoji]]
match = "((^ğŸ‡¹ğŸ‡­)|(\\bTH[A](?:[-_\\s]?\\d+|_)?\\b)|(Thailand)|(æ³°å›½)|(æ³°åœ‹)|(æ›¼è°·))"
emoji = "ğŸ‡¹ğŸ‡­"

[[emoji]]
match = "((^ğŸ‡¹ğŸ‡·)|(\\bT[U]R(?:[-_\\s]?\\d+|_)?\\b)|(Turkey)|(TÃ¼rkiye)|(ä¼Šæ–¯å¦å¸ƒå°”)|(åœŸ(è€³å…¶)?(?!â–·|å›|è½¬)))"
emoji = "ğŸ‡¹ğŸ‡·"

[[emoji]]
match = "((^ğŸ‡ºğŸ‡¦)|(\\bUA(?:[-_\\s]?\\d+|_)?\\b)|(Ukraine)|(ä¹Œå…‹å…°))"
emoji = "ğŸ‡ºğŸ‡¦"

[[emoji]]
match = "((^ğŸ‡»ğŸ‡³)|(\\bVN(?:[-_\\s]?\\d+|_)?\\b)|(Vietnam)|(è¶Šå—))"
emoji = "ğŸ‡»ğŸ‡³"

[[emoji]]
match = "((^ğŸ‡¿ğŸ‡¦)|(\\bZA(?:[-_\\s]?\\d+|_)?\\b)|(Africa)|(å—é))"
emoji = "ğŸ‡¿ğŸ‡¦"

[[emoji]]
match = "(?i:(^ğŸ‡¦ğŸ‡º)|(\\bAU[S]?(?:[-_\\s]?\\d+|_)?\\b)|(Australia)|(Sydney)|(æ¾³å¤§åˆ©äºš)|(æ¾³æ´²)|(æ‚‰å°¼))"
emoji = "ğŸ‡¦ğŸ‡º"

[[emoji]]
match = "(?i:(^ğŸ‡©ğŸ‡°)|(\\bD[N]?K(?:[-_\\s]?\\d+|_)?\\b)|(Denmark)|(ä¸¹éº¦))"
emoji = "ğŸ‡©ğŸ‡°"

[[emoji]]
match = "(?i:(^ğŸ‡©ğŸ‡ª)|(\\bDEU?(?:[-_\\s]?\\d+|_)?\\b)|(Germany)|(Frankfurt)|(æ³•å…°å…‹ç¦)|(å¾·(å›½|æ„å¿—)?(?!â–·|å›|è½¬))|(ä¸­å¾·))"
emoji = "ğŸ‡©ğŸ‡ª"

[[emoji]]
match = "(?i:(^ğŸ‡ªğŸ‡¸)|(\\bES[P]?(?:[-_\\s]?\\d+|_)?\\b)|(Spain)|(è¥¿ç­ç‰™))"
emoji = "ğŸ‡ªğŸ‡¸"

[[emoji]]
match = "(?i:(^ğŸ‡«ğŸ‡·)|(\\bFR[A]?(?:[-_\\s]?\\d+|_)?\\b)|(France)|(Paris)|(æ³•(å›½)?(?!â–·|å›|è½¬))|(å·´é»))"
emoji = "ğŸ‡«ğŸ‡·"

[[emoji]]
match = "(?i:(^ğŸ‡®ğŸ‡³)|(\\bIN[D]?(?:[-_\\s]?\\d+|_)?\\b)|(India)|(Mumbai)|(å°åº¦)|(å­Ÿä¹°)|(åŠ å°”å„ç­”)|(è´¾åå¾·)|(æ³°ç±³å°”çº³å¾·))"
emoji = "ğŸ‡®ğŸ‡³"

[[emoji]]
match = "(?i:(^ğŸ‡®ğŸ‡¸)|(\\bIS[L]?(?:[-_\\s]?\\d+|_)?\\b)|(Iceland)|(å†°å²›))"
emoji = "ğŸ‡®ğŸ‡¸"

[[emoji]]
match = "(?i:(^ğŸ‡°ğŸ‡µ)|(\\bKP(?:[-_\\s]?\\d+|_)?\\b)|(North.*?K(orea|OR|R)\\s?\\d*)|(æœé²œ))"
emoji = "ğŸ‡°ğŸ‡µ"

[[emoji]]
match = "(?i:(^ğŸ‡³ğŸ‡±)|(\\bNL[D]?(?:[-_\\s]?\\d+|_)?\\b)|(Netherlands)|(è·å…°)|(é˜¿å§†æ–¯ç‰¹ä¸¹))"
emoji = "ğŸ‡³ğŸ‡±"

[[emoji]]
match = "(?i:(^ğŸ‡µğŸ‡­)|(\\bP[O]?H(?:[-_\\s]?\\d+|_)?\\b)|(Philippines)|(è²å¾‹å®¾)|(é©¬å°¼æ‹‰))"
emoji = "ğŸ‡µğŸ‡­"

[[emoji]]
match = "(?i:(^ğŸ‡µğŸ‡±)|(\\bP[O]?L(?:[-_\\s]?\\d+|_)?\\b)|(Poland)|(æ³¢å…°))"
emoji = "ğŸ‡µğŸ‡±"

[[emoji]]
match = "(?i:(^ğŸ‡¦ğŸ‡ª)|(\\bUAE(?:[-_\\s]?\\d+|_)?\\b)|(Dubai)|(é˜¿è”é…‹)|(è¿ªæ‹œ)|(é˜¿æ‹‰ä¼¯é…‹é•¿å›½))"
emoji = "ğŸ‡¦ğŸ‡ª"

[[emoji]]
match = "(?i:(^ğŸ‡¨ğŸ‡¦)|(\\bCA[N]?(?:[-_\\s]?\\d+|_)?\\b)|(Canada)|(Toronto|Montreal|Vancouver)|(è’™ç‰¹åˆ©å°”|æ¸©å“¥å|æ¥“è‘‰|æ«å¶)|(åŠ (æ‹¿å¤§)?(?!å·|å¡|æ‹‰|å“¥|åˆ©|â–·|å›|è½¬)))"
emoji = "ğŸ‡¨ğŸ‡¦"

[[emoji]]
match = "(?i:(^ğŸ‡¯ğŸ‡µ)|(\\bJP[N]?(?:[-_\\s]?\\d+|_)?\\b)|(Japan)|(Tokyo|Osaka|Saitama)|(ä¸œäº¬|å¤§é˜ª|åŸ¼ç‰|äº¬éƒ½)|(æ—¥(æœ¬)?(?!â–·|å›|è½¬))|([^\\-]æ—¥)|(æ²ªæ—¥|ç©—æ—¥|å·æ—¥|ä¸­æ—¥|æ³‰æ—¥|æ­æ—¥))"
emoji = "ğŸ‡¯ğŸ‡µ"

[[emoji]]
match = "(?i:(^ğŸ‡°ğŸ‡·)|((?<!North\\s)\\bK(orea|OR|R)(?:[-_\\s]?\\d+|_)?\\b)|(é¦–å°”)|(éŸ©)|(éŸ“))"
emoji = "ğŸ‡°ğŸ‡·"

[[emoji]]
match = "(?i:(^ğŸ‡·ğŸ‡º)|(\\bRU[S]?(?:[-_\\s]?\\d+|_)?\\b)|(Russia)|(Moscow|Petersburg|Siberia)|(è«æ–¯ç§‘|åœ£å½¼å¾—å ¡|è¥¿ä¼¯åˆ©äºš|æ–°è¥¿ä¼¯åˆ©äºš|å“ˆå·´ç½—å¤«æ–¯å…‹|ä¼¯åŠ›)|(ä¿„(ç½—æ–¯)?(?!â–·|å›|è½¬))|([^\\-]ä¿„)|(äº¬ä¿„|æ­ä¿„))"
emoji = "ğŸ‡·ğŸ‡º"

[[emoji]]
match = "(?i:(^ğŸ‡¸ğŸ‡¬)|(\\bSG[P]?(?:[-_\\s]?\\d+|_)?\\b)|(Singapore)|(ç‹®åŸ|ç…åŸ)|(æ–°(åŠ å¡)?(?!â–·|è¥¿å…°|åŒ—|ç–†))|(æ²ªæ–°|äº¬æ–°|æ³‰æ–°|ç©—æ–°|æ·±æ–°|æ­æ–°))"
emoji = "ğŸ‡¸ğŸ‡¬"

[[emoji]]
match = "(?i:(^ğŸ‡¬ğŸ‡§)|(\\bUK(?:[-_\\s]?\\d+|_)?\\b)|(\\bGB[R]?(?:[-_\\s]?\\d+|_)?\\b)|(England)|(United.*?Kingdom)|(London)|(è‹±(å›½|æ ¼å…°)?(?!â–·|å›|è½¬))|([^\\-]è‹±)|(ä¼¦æ•¦))"
emoji = "ğŸ‡¬ğŸ‡§"

[[emoji]]
match = "(?i:(^ğŸ‡ºğŸ‡¸)|(\\bUS[A]?(?:[-_\\s]?\\d+|_)?\\b)|(America)|(United.*?States)|(ç¾(å›½)?(?!â–·|å›|è½¬))|([^\\-]ç¾)|(æ³¢ç‰¹å…°|è¾¾æ‹‰æ–¯|ä¿„å‹’å†ˆ|å‡¤å‡°åŸ|è´¹åˆ©è’™|ç¡…è°·|æ‹‰æ–¯ç»´åŠ æ–¯|æ´›æ‰çŸ¶|åœ£ä½•å¡|åœ£å…‹æ‹‰æ‹‰|è¥¿é›…å›¾|èŠåŠ å“¥|ç›æ¹–åŸ|æ°´ç‰›åŸ|æ²ªç¾|äº¬ç¾))"
emoji = "ğŸ‡ºğŸ‡¸"

[[emoji]]
match = "(?i:(^ğŸ‡­ğŸ‡°)|(\\bHK[G]?(?:[-_\\s]?\\d+|_)?\\b)|(Hong.*?Kong)|(\\b(HKT|HKBN|HGC|WTT|CMI)\\d*\\b)|(æ¸¯(?!â–·|å›|è½¬))|([^\\-]æ¸¯))"
emoji = "ğŸ‡­ğŸ‡°"

[[emoji]]
match = "(?i:(^ğŸ‡²ğŸ‡´)|(\\bMO(?:[-_\\s]?\\d+|_)?\\b)|(Macao)|(æ¾³é—¨)|(\\bCTM\\b)|(æ¾³(é—¨)?(?!å¤§åˆ©äºš|â–·|å›|è½¬)))"
emoji = "ğŸ‡²ğŸ‡´"

[[emoji]]
match = "(?i:(^ğŸ‡¹ğŸ‡¼)|(\\bTW[N]?(?:[-_\\s]?\\d+|_)?\\b)|(Taiwan)|(\\b(CHT|HINET)\\b)|(æ–°åŒ—|å½°åŒ–)|(å°(æ¹¾|åŒ—|ä¸­)?(?!â–·|å›|è½¬))|([^\\-]å°))"
emoji = "ğŸ‡¹ğŸ‡¼"

[[emoji]]
match = "(?i:(^ğŸ‡¨ğŸ‡³)|(\\bC[H]?N(?:[-_\\s]?\\d+|_)?\\b)|(China)|(back)|(å›å›½)|(ä¸­(å›½)?(?!é|â–·|å›|è½¬))|((æ²³åŒ—|å±±è¥¿|è¾½å®|å‰æ—|é»‘é¾™æ±Ÿ|æ±Ÿè‹|æµ™æ±Ÿ|å®‰å¾½|ç¦å»º|æ±Ÿè¥¿|å±±ä¸œ|æ²³å—|æ¹–åŒ—|æ¹–å—|å¹¿ä¸œ|æµ·å—|å››å·|è´µå·|äº‘å—|é™•è¥¿|ç”˜è‚ƒ|é’æµ·|å†…è’™å¤|å¹¿è¥¿|è¥¿è—|å®å¤|æ–°ç–†|åŒ—äº¬|ä¸Šæµ·|å¤©æ´¥|é‡åº†|å¹¿å·|æ·±åœ³|æ­å·|æˆéƒ½|å—äº¬|æ­¦æ±‰|è¥¿å®‰|è‹å·|å¸¸å·|å¾å·|é’å²›|å®æ³¢|é•‡æ±Ÿ|åˆè‚¥)[^\\-])|(((äº¬(?!éƒ½)|æ²ª|ç©—|è‹|æ­|å¾|é’|ç”¬|é•‡|ç¦…|è“‰)(å·|å²›|æ±Ÿ)?)(?!â–·|å›|è½¬))|(æ·±(?!â–·|æ¸¯)))"
emoji = "ğŸ‡¨ğŸ‡³"

[[emoji]]
match = "((^ğŸ‡ªğŸ‡º)|(\\bEU(?:[-_\\s]?\\d+|_)?\\b)|(Europe)|(æ¬§æ´²))"
emoji = "ğŸ‡ªğŸ‡º"
