[[emoji]]
match = "(?i:Bandwidth|expire|æµé‡|æ—¶é—´|åº”æ€¥|è¿‡æœŸ)"
emoji = "ğŸ³ï¸â€ğŸŒˆ"

[[emoji]]
match = "(NetEaseMusic|ç½‘æ˜“äº‘éŸ³ä¹|ç½‘æ˜“äº‘è§£é”)"
emoji = "ğŸ¶"

[[emoji]]
match = "(\\bAL\\d*|AL_\\b|é˜¿å°”å·´å°¼äºš|Albania)"
emoji = "ğŸ‡¦ğŸ‡±"

[[emoji]]
match = "(\\bOM\\d*|OM_\\b|é˜¿æ›¼è‹ä¸¹|é©¬æ–¯å–€ç‰¹|Muscat)"
emoji = "ğŸ‡´ğŸ‡²"

[[emoji]]
match = "(\\bAZ\\d*|AZ_\\b|é˜¿å¡æ‹œç–†|Azerbaijan)"
emoji = "ğŸ‡¦ğŸ‡¿"

[[emoji]]
match = "(\\bEG\\d*|EG_\\b|åŸƒåŠ|Egypt)"
emoji = "ğŸ‡ªğŸ‡¬"

[[emoji]]
match = "(\\bEE\\d*|EE_\\b|çˆ±æ²™å°¼äºš|Estonia)"
emoji = "ğŸ‡ªğŸ‡ª"

[[emoji]]
match = "(\\bBH\\d*|BH_\\b|å·´æ—|Bahrain)"
emoji = "ğŸ‡§ğŸ‡­"

[[emoji]]
match = "(\\bBT\\d*|BT_\\b|ä¸ä¸¹|Bhutan)"
emoji = "ğŸ‡§ğŸ‡¹"

[[emoji]]
match = "(\\bPA\\d*|PA_\\b|å·´æ‹¿é©¬|Panama)"
emoji = "ğŸ‡µğŸ‡¦"

[[emoji]]
match = "(\\bBG\\d*|BG_\\b|ä¿åŠ åˆ©äºš|Bulgaria)"
emoji = "ğŸ‡§ğŸ‡¬"

[[emoji]]
match = "(\\bMK\\d*|MK_\\b|åŒ—é©¬å…¶é¡¿|Macedonia)"
emoji = "ğŸ‡²ğŸ‡°"

[[emoji]]
match = "(\\bBA\\d*|BA_\\b|æ³¢é»‘å…±å’Œå›½|æ³¢å£«å°¼äºšä¸èµ«å¡å“¥ç»´çº³|Bosnia|Herzegovina)"
emoji = "ğŸ‡§ğŸ‡¦"

[[emoji]]
match = "(\\bVA\\d*|VA_\\b|æ¢µè’‚å†ˆ|Vatican)"
emoji = "ğŸ‡»ğŸ‡¦"

[[emoji]]
match = "(\\bGE\\d*|GE_\\b|æ ¼é²å‰äºš|Georgia)"
emoji = "ğŸ‡¬ğŸ‡ª"

[[emoji]]
match = "(\\bKZ\\d*|KZ_\\b|å“ˆè¨å…‹æ–¯å¦|Kazakhstan)"
emoji = "ğŸ‡°ğŸ‡¿"

[[emoji]]
match = "(\\bKG\\d*|KG_\\b|å‰å°”å‰æ–¯æ–¯å¦|Kyrgyzstan)"
emoji = "ğŸ‡°ğŸ‡¬"

[[emoji]]
match = "(\\bKH\\d*|KH_\\b|æŸ¬åŸ”å¯¨|Cambodia)"
emoji = "ğŸ‡°ğŸ‡­"

[[emoji]]
match = "(\\bHR\\d*|HR_\\b|å…‹ç½—åœ°äºš|Croatia)"
emoji = "ğŸ‡­ğŸ‡·"

[[emoji]]
match = "(\\bKE\\d*|KE_\\b|è‚¯å°¼äºš|Kenya)"
emoji = "ğŸ‡°ğŸ‡ª"

[[emoji]]
match = "(\\bLA\\d*|LA_\\b|è€æŒ|Vientiane|Laos)"
emoji = "ğŸ‡±ğŸ‡¦"

[[emoji]]
match = "(\\bLV\\d*|LV_\\b|æ‹‰è„±ç»´äºš|Latvia)"
emoji = "ğŸ‡±ğŸ‡»"

[[emoji]]
match = "(\\bLT\\d*|LT_\\b|ç«‹é™¶å®›|Lietuvos)"
emoji = "ğŸ‡±ğŸ‡¹"

[[emoji]]
match = "(\\bLU\\d*|LU_\\b|å¢æ£®å ¡|Luxemburg|Luxembourg)"
emoji = "ğŸ‡±ğŸ‡º"

[[emoji]]
match = "(\\bMN\\d*|MN_\\b|è’™å¤|ĞœĞ¾Ğ½Ğ³Ğ¾Ğ»ÑƒĞ»Ñ|Mongolia)"
emoji = "ğŸ‡²ğŸ‡³"

[[emoji]]
match = "(\\bPE\\d*|PE_\\b|ç§˜é²|Peru)"
emoji = "ğŸ‡µğŸ‡ª"

[[emoji]]
match = "(\\bMM\\d*|MM_\\b|ç¼…ç”¸|Myanmar)"
emoji = "ğŸ‡²ğŸ‡²"

[[emoji]]
match = "(\\bMX\\d*|MX_\\b|å¢¨è¥¿å“¥|Mexico)"
emoji = "ğŸ‡²ğŸ‡½"

[[emoji]]
match = "(\\bAQ\\d*|AQ_\\b|å—æ|Antarctica)"
emoji = "ğŸ‡¦ğŸ‡¶"

[[emoji]]
match = "(\\bNG\\d*|NG_\\b|å°¼æ—¥åˆ©äºš|Nigeria)"
emoji = "ğŸ‡³ğŸ‡¬"

[[emoji]]
match = "(\\bPT\\d*|PT_\\b|è‘¡è„ç‰™|Portugal)"
emoji = "ğŸ‡µğŸ‡¹"

[[emoji]]
match = "(\\bQA\\d*|QA_\\b|å¡å¡”å°”|Qatar)"
emoji = "ğŸ‡¶ğŸ‡¦"

[[emoji]]
match = "(\\bRS\\d*|RS_\\b|å¡å°”ç»´äºš|Serbia)"
emoji = "ğŸ‡·ğŸ‡¸"

[[emoji]]
match = "(\\bCY\\d*|CY_\\b|å¡æµ¦è·¯æ–¯|Cyprus)"
emoji = "ğŸ‡¨ğŸ‡¾"

[[emoji]]
match = "(\\bSK\\d*|SK_\\b|æ–¯æ´›ä¼å…‹|Slovensko)"
emoji = "ğŸ‡¸ğŸ‡°"

[[emoji]]
match = "(\\bSI\\d*|SI_\\b|æ–¯æ´›æ–‡å°¼äºš|Slovenia)"
emoji = "ğŸ‡¸ğŸ‡®"

[[emoji]]
match = "(\\bTN\\d*|TN_\\b|çªå°¼æ–¯|Tunisia)"
emoji = "ğŸ‡¹ğŸ‡³"

[[emoji]]
match = "(\\bUY\\d*|UY_\\b|ä¹Œæ‹‰åœ­|Uruguay)"
emoji = "ğŸ‡ºğŸ‡¾"

[[emoji]]
match = "(\\bGR\\d*|GR_\\b|å¸Œè…Š|Greece)"
emoji = "ğŸ‡¬ğŸ‡·"

[[emoji]]
match = "(\\bNZ\\d*|NZ_\\b|æ–°è¥¿å…°|çº½è¥¿å…°|New Zealand)"
emoji = "ğŸ‡³ğŸ‡¿"

[[emoji]]
match = "(\\bIR\\d*|IR_\\b|ä¼Šæœ—|Iran)"
emoji = "ğŸ‡®ğŸ‡·"

[[emoji]]
match = "(\\bJO\\d*|JO_\\b|çº¦æ—¦|Jordan)"
emoji = "ğŸ‡¯ğŸ‡´"

[[emoji]]
match = "(\\bCL\\d*|CL_\\b|æ™ºåˆ©|æ™ºåŠ›|Chile)"
emoji = "ğŸ‡¨ğŸ‡±"

[[emoji]]
match = "(\\bAC\\d*|AC_\\b|Ascension|é˜¿æ£®æ¾)"
emoji = "ğŸ‡¦ğŸ‡¨"

[[emoji]]
match = "(\\bAT\\d*|AT_\\b|Austria|Vienna|å¥¥åœ°åˆ©|ç»´ä¹Ÿçº³)"
emoji = "ğŸ‡¦ğŸ‡¹"

[[emoji]]
match = "(\\bBD\\d*|BD_\\b|Bengal|Bangladesh|å­ŸåŠ æ‹‰)"
emoji = "ğŸ‡§ğŸ‡©"

[[emoji]]
match = "(\\bCO\\d*|CO_\\b|Colombia|å“¥ä¼¦æ¯”äºš)"
emoji = "ğŸ‡¨ğŸ‡´"

[[emoji]]
match = "(\\bCR\\d*|CR_\\b|Costa Rica|å“¥æ–¯è¾¾é»åŠ )"
emoji = "ğŸ‡¨ğŸ‡·"

[[emoji]]
match = "(\\bCZ\\d*|CZ_\\b|Czech|æ·å…‹)"
emoji = "ğŸ‡¨ğŸ‡¿"

[[emoji]]
match = "(\\bEC\\d*|EC_\\b|Ecuador|å„ç“œå¤šå°”)"
emoji = "ğŸ‡ªğŸ‡¨"

[[emoji]]
match = "(\\bEU\\d*|EU_\\b|Europe|æ¬§æ´²)"
emoji = "ğŸ‡ªğŸ‡º"

[[emoji]]
match = "(\\bFI\\d*|FI_\\b|Finland|Helsinki|èŠ¬å…°|èµ«å°”è¾›åŸº)"
emoji = "ğŸ‡«ğŸ‡®"

[[emoji]]
match = "(\\bHU\\d*|HU_\\b|Hungary|åŒˆç‰™åˆ©)"
emoji = "ğŸ‡­ğŸ‡º"

[[emoji]]
match = "(\\bIM\\d*|IM_\\b|IMAN|é©¬æ©å²›|Mann)"
emoji = "ğŸ‡®ğŸ‡²"

[[emoji]]
match = "(\\bID\\d*|ID_\\b|Indonesia|Jakarta|å°å°¼|å°åº¦å°¼è¥¿äºš|é›…åŠ è¾¾)"
emoji = "ğŸ‡®ğŸ‡©"

[[emoji]]
match = "(\\bIE\\d*|IE_\\b|Ireland|Dublin|çˆ±å°”å…°|éƒ½æŸæ—)"
emoji = "ğŸ‡®ğŸ‡ª"

[[emoji]]
match = "(\\bIL\\d*|IL_\\b|Israel|ä»¥è‰²åˆ—)"
emoji = "ğŸ‡®ğŸ‡±"

[[emoji]]
match = "(\\bIT\\d*|IT_\\b|Italy|Milan|æ„å¤§åˆ©|ç±³å…°)"
emoji = "ğŸ‡®ğŸ‡¹"

[[emoji]]
match = "(\\bMD\\d*|MD_\\b|Moldova|æ‘©å°”å¤šç“¦)"
emoji = "ğŸ‡²ğŸ‡©"

[[emoji]]
match = "(\\bMA\\d*|MA_\\b|Morocco|æ‘©æ´›å“¥)"
emoji = "ğŸ‡²ğŸ‡¦"

[[emoji]]
match = "(\\bNP\\d*|NP_\\b|Nepal|å°¼æ³Šå°”)"
emoji = "ğŸ‡³ğŸ‡µ"

[[emoji]]
match = "(\\bNO\\d*|NO_\\b|Norway|æŒªå¨)"
emoji = "ğŸ‡³ğŸ‡´"

[[emoji]]
match = "(\\bPK\\d*|PK_\\b|Pakistan|å·´åŸºæ–¯å¦)"
emoji = "ğŸ‡µğŸ‡°"

[[emoji]]
match = "(\\bPR\\d*|PR_\\b|Puerto.*?Rico|æ³¢å¤šé»å„)"
emoji = "ğŸ‡µğŸ‡·"

[[emoji]]
match = "(\\bCH\\d*|CH_\\b|Switzerland|Zurich|ç‘å£«|è‹é»ä¸–)"
emoji = "ğŸ‡¨ğŸ‡­"

[[emoji]]
match = "(\\bVE\\d*|VE_\\b|Venezuela|å§”å†…ç‘æ‹‰)"
emoji = "ğŸ‡»ğŸ‡ª"

[[emoji]]
match = "(\\bAR\\d*|AR_\\b|é˜¿æ ¹å»·|Argentina)"
emoji = "ğŸ‡¦ğŸ‡·"

[[emoji]]
match = "(\\bBE\\d*|BE_\\b|Belgium|æ¯”åˆ©æ—¶)"
emoji = "ğŸ‡§ğŸ‡ª"

[[emoji]]
match = "(\\bBR\\d*|BR_\\b|Brazil|Paulo|å·´è¥¿|åœ£ä¿ç½—)"
emoji = "ğŸ‡§ğŸ‡·"

[[emoji]]
match = "(\\bMY\\d*|MY_\\b|Malaysia|é©¬æ¥è¥¿äºš)"
emoji = "ğŸ‡²ğŸ‡¾"

[[emoji]]
match = "(\\bRO\\d*|RO_\\b|Romania|ç½—é©¬å°¼äºš)"
emoji = "ğŸ‡·ğŸ‡´"

[[emoji]]
match = "(\\bSA\\d*|SA_\\b|Arabia|æ²™ç‰¹)"
emoji = "ğŸ‡¸ğŸ‡¦"

[[emoji]]
match = "(\\bSE\\d*|SE_\\b|Sweden|ç‘å…¸)"
emoji = "ğŸ‡¸ğŸ‡ª"

[[emoji]]
match = "(\\bTH[A]|TH_\\b|Thailand|æ³°å›½|æ³°åœ‹|æ›¼è°·)"
emoji = "ğŸ‡¹ğŸ‡­"

[[emoji]]
match = "(\\bT[U]R|TR_\\b|Turkey|TÃ¼rkiye|åœŸè€³å…¶|ä¼Šæ–¯å¦å¸ƒå°”|åœŸ.*(?!â–·|å›|è½¬))"
emoji = "ğŸ‡¹ğŸ‡·"

[[emoji]]
match = "(\\bUA\\d*|UA_\\b|Ukraine|ä¹Œå…‹å…°)"
emoji = "ğŸ‡ºğŸ‡¦"

[[emoji]]
match = "(\\bVN\\d*|VN_\\b|Vietnam|è¶Šå—)"
emoji = "ğŸ‡»ğŸ‡³"

[[emoji]]
match = "(\\bZA\\d*|ZA_\\b|Africa|å—é)"
emoji = "ğŸ‡¿ğŸ‡¦"

[[emoji]]
match = "(?i:\\bAU[S]?\\d*|AU_\\b|Australia|Sydney|æ¾³å¤§åˆ©äºš|æ¾³æ´²|æ‚‰å°¼)"
emoji = "ğŸ‡¦ğŸ‡º"

[[emoji]]
match = "(?i:\\bD[N]?K|DK_\\b|Denmark|ä¸¹éº¦)"
emoji = "ğŸ‡©ğŸ‡°"

[[emoji]]
match = "(?i:\\bDE[U]?\\d*|DE_\\b|Germany|æ³•å…°å…‹ç¦|å¾·(å›½|æ„å¿—)|ä¸­å¾·|^å¾·$|å¾·.*(?!â–·|å›|è½¬))"
emoji = "ğŸ‡©ğŸ‡ª"

[[emoji]]
match = "(?i:\\bES[P]?\\d*|ES_\\b|Spain|è¥¿ç­ç‰™)"
emoji = "ğŸ‡ªğŸ‡¸"

[[emoji]]
match = "(?i:\\bFR[A]?\\d*|FR_\\b|France|Paris|æ³•å›½|å·´é»|æ³•å›½.*(?!â–·|å›|è½¬))"
emoji = "ğŸ‡«ğŸ‡·"

[[emoji]]
match = "(?i:\\bIN[D]?\\d*|IN_\\b|India|Mumbai|å°åº¦|å­Ÿä¹°|åŠ å°”å„ç­”|è´¾åå¾·|æ³°ç±³å°”çº³å¾·)"
emoji = "ğŸ‡®ğŸ‡³"

[[emoji]]
match = "(?i:\\bIS[L]?\\d*|IS_\\b|Iceland|å†°å²›)"
emoji = "ğŸ‡®ğŸ‡¸"

[[emoji]]
match = "(?i:\\bKP\\d*|KP_\\b|North.*?Korea|æœé²œ)"
emoji = "ğŸ‡°ğŸ‡µ"

[[emoji]]
match = "(?i:\\bNL[D]?\\d*|NL_\\b|Netherlands|è·å…°|é˜¿å§†æ–¯ç‰¹ä¸¹)"
emoji = "ğŸ‡³ğŸ‡±"

[[emoji]]
match = "(?i:\\bP[O]?H\\d*|PH_\\b|Philippines|è²å¾‹å®¾|é©¬å°¼æ‹‰)"
emoji = "ğŸ‡µğŸ‡­"

[[emoji]]
match = "(?i:\\bP[O]?L|PL_\\b|Poland|æ³¢å…°)"
emoji = "ğŸ‡µğŸ‡±"

[[emoji]]
match = "(?i:\\bUAE|UAE_\\b|Dubai|é˜¿è”é…‹|è¿ªæ‹œ)"
emoji = "ğŸ‡¦ğŸ‡ª"

[[emoji]]
match = "(?i:\\bCA[N]?\\d*|CA_\\b|Canada|Toronto|Montreal|Vancouver|åŠ æ‹¿å¤§|è’™ç‰¹åˆ©å°”|æ¸©å“¥å|æ¥“è‘‰|æ«å¶|åŠ (?!å·|å¡|æ‹‰|å“¥).*(?!â–·|å›|è½¬))"
emoji = "ğŸ‡¨ğŸ‡¦"

[[emoji]]
match = "(?i:\\bJP[N]?\\d*|JP_\\b|Japan|Tokyo|Osaka|Saitama|æ—¥æœ¬|ä¸œäº¬|å¤§é˜ª|åŸ¼ç‰|[^-]æ—¥|æ—¥.*(?!â–·|å›|è½¬)|æ²ªæ—¥|ç©—æ—¥|å·æ—¥|ä¸­æ—¥|æ³‰æ—¥|æ­æ—¥)"
emoji = "ğŸ‡¯ğŸ‡µ"

[[emoji]]
match = "(?i:(?<!North\\s)(\\bK[O]?R\\d*|KR_\\b|Korea|é¦–å°”|éŸ©|éŸ“))"
emoji = "ğŸ‡°ğŸ‡·"

[[emoji]]
match = "(?i:\\bRU[S]?\\d*|RU_\\b|Russia|Moscow|Petersburg|Siberia|ä¼¯åŠ›|è«æ–¯ç§‘|åœ£å½¼å¾—å ¡|è¥¿ä¼¯åˆ©äºš|æ–°è¥¿ä¼¯åˆ©äºš|å“ˆå·´ç½—å¤«æ–¯å…‹|ä¿„ç½—æ–¯|[^-]ä¿„|ä¿„.*(?!â–·|å›|è½¬)|äº¬ä¿„|æ­ä¿„)"
emoji = "ğŸ‡·ğŸ‡º"

[[emoji]]
match = "(?i:\\bSG[P]?\\d*|SG_\\b|Singapore|æ–°åŠ å¡|ç‹®åŸ|ç…åŸ|[^-]æ–°|æ–°(?!â–·|è¥¿)|æ²ªæ–°|äº¬æ–°|æ³‰æ–°|ç©—æ–°|æ·±æ–°|æ­æ–°)"
emoji = "ğŸ‡¸ğŸ‡¬"

[[emoji]]
match = "(?i:\\bUK\\d*|UK_\\b|\\bGB[R]?\\d*|GB_\\b|England|United.*?Kingdom|London|è‹±å›½|[^-]è‹±|ä¼¦æ•¦|è‹±.*(?!â–·|å›|è½¬))"
emoji = "ğŸ‡¬ğŸ‡§"

[[emoji]]
match = "(?i:\\bUS[A]?\\d*|US_\\b|America|United.*?States|ç¾å›½|[^-]ç¾|æ³¢ç‰¹å…°|è¾¾æ‹‰æ–¯|ä¿„å‹’å†ˆ|å‡¤å‡°åŸ|è´¹åˆ©è’™|ç¡…è°·|æ‹‰æ–¯ç»´åŠ æ–¯|æ´›æ‰çŸ¶|åœ£ä½•å¡|åœ£å…‹æ‹‰æ‹‰|è¥¿é›…å›¾|èŠåŠ å“¥|ç¾.*(?!â–·|å›|è½¬)|æ²ªç¾|äº¬ç¾)"
emoji = "ğŸ‡ºğŸ‡¸"

[[emoji]]
match = "(?i:\\bHK[G]?\\d*|HK_\\b|Hong.*?Kong|\\bHKT\\d*\\b|\\bHKBN\\d*\\b|\\bHGC\\d*\\b|\\bWTT\\d*\\b|\\bCMI\\d*\\b|\\bHK\\d*\\b|[^-]æ¸¯|æ¸¯(?!â–·|å›|è½¬))"
emoji = "ğŸ‡­ğŸ‡°"

[[emoji]]
match = "(?i:\\bMO\\d*|MO_\\b|Macao|æ¾³é—¨|\\bCTM\\b|æ¾³(?!å¤§åˆ©äºš).*(?!â–·|å›|è½¬))"
emoji = "ğŸ‡²ğŸ‡´"

[[emoji]]
match = "(?i:\\bTW[N]?\\d*|TW_\\b|Taiwan|æ–°åŒ—|å½°åŒ–|\\bCHT\\b|å°æ¹¾|[^-]å°|\\bHINET\\b|å°.*(?!â–·|å›|è½¬)|å°åŒ—|å°ä¸­)"
emoji = "ğŸ‡¹ğŸ‡¼"

[[emoji]]
match = "(?i:\\bC[H]?N|CN_\\b|China|back|å›å›½|ä¸­å›½[^-]|æ±Ÿè‹[^-]|åŒ—äº¬[^-]|ä¸Šæµ·[^-]|å¹¿å·[^-]|æ·±åœ³[^-]|æ­å·[^-]|å¸¸å·[^-]|å¾å·[^-]|é’å²›[^-]|å®æ³¢[^-]|é•‡æ±Ÿ[^-]|æˆéƒ½[^-]|æ²³åŒ—[^-]|å±±è¥¿[^-]|è¾½å®[^-]|å‰æ—[^-]|é»‘é¾™æ±Ÿ[^-]|æ±Ÿè‹[^-]|æµ™æ±Ÿ[^-]|å®‰å¾½[^-]|ç¦å»º[^-]|æ±Ÿè¥¿[^-]|å±±ä¸œ[^-]|æ²³å—[^-]|æ¹–åŒ—[^-]|æ¹–å—[^-]|å¹¿ä¸œ[^-]|æµ·å—[^-]|å››å·[^-]|è´µå·[^-]|äº‘å—[^-]|é™•è¥¿[^-]|ç”˜è‚ƒ[^-]|é’æµ·[^-]|å†…è’™å¤[^-]|å¹¿è¥¿[^-]|è¥¿è—[^-]|å®å¤[^-]|æ–°ç–†[^-]|ä¸­.*(?!â–·|å›|è½¬)|è‹.*(?!â–·|å›|è½¬)|äº¬.*(?!â–·|å›|è½¬)|æ²ª.*(?!â–·|å›|è½¬)|ç©—.*(?!â–·|å›|è½¬)|æ·±(?!â–·|æ¸¯)|æ­.*(?!â–·|å›|è½¬)|å¾.*(?!â–·|å›|è½¬)|é’.*(?!â–·|å›|è½¬)|ç”¬.*(?!â–·|å›|è½¬)|é•‡.*(?!â–·|å›|è½¬)|ç¦….*(?!â–·|å›|è½¬)|è“‰.*(?!â–·|å›|è½¬))"
emoji = "ğŸ‡¨ğŸ‡³"
