# short names
[[rename_node]]
match = "(è§£é”|)(\\|)(x.*)(\\|V2ray)"
replace = "$[$3]"

[[rename_node]]
match = "(..|...)(\\d\\d\\d\\d|\\d\\d\\d)(\\|)(Azure|HKT|CN2GIA)"
replace = "$1$4$2"

[[rename_node]]
match = "((^CordCloud - )|(å…³æ³¨TG@txwl666)|(ä¸€å…ƒæœºåœº:ssrsub.de)|(æœºåœºæ¨è:dafei.de)|(æœºåœºæ¨è:)|(FIBERSTATE LLC)|(PCCW IMS)|(PCCW IMS LIMITED))"
replace = ""

[[rename_node]]
match = "(æ ‡å‡†)|(æ ‡å‡†çº¿è·¯)|(çº¿è·¯)|(ä¸­è½¬)|(ç›´è¿)|(80ç«¯å£)|(V\\d-)|((IEPL)|(IEPLä¸“çº¿)|(IPLC)|(IPLCä¸“çº¿))|(IPV6)|((æµ·å¤–\\|æ–°ç–†ä¸“ç”¨))|((\u6d77\u5916\\|\u65b0\u7586\u4e13\u7528)|(CLOUD))"
replace = ""

[[rename_node]]
match = "(.*)( )(.*\\d)( \\| )(.*)"
replace = "$1$3$5"

[[rename_node]]
match = "(.*)(\\b\\d.*\\d\\b)(é™æ€è§£é”|åŠ¨æ€è§£é”|åŸç”Ÿè§£é”|è§£é”|åŠ¨æ€åŸç”Ÿ|é™æ€åŸç”Ÿ|åŸç”Ÿ|å®¶å®½)"
replace = "$1$2[M]"

[[rename_node]]
match = "(.*)(\\d.*\\d)(\\|[\\w].*\\d)"
replace = "$1$2"

[[rename_node]]
match = "(?i)(.*?\\p{Han})(?:NO)[.\\-]?(\\d+[A-Za-z0-9\\-]*)$"
replace = "$1 $2"

# [[rename_node]]
# match = "(ã€Œ|\u300c)(\\p{RI}\\p{RI})(ã€|\u300d)"
# replace = "$2 "

[[rename_node]]
match = "((CN\\dâ€¢)|^)(â“ª|â¶|â·|â¸|â»)(TJ\\.|gR\\.|V2\\.|H2\\.|SS\\.)"
replace = ""

[[rename_node]]
match = "(å•†å®½)|(\\dç»„)|(--)|(â—†)"
replace = ""

[[rename_node]]
match = "^(.*)(?i:\\bHK[G]?\\d*\\b|Hong.*?Kong|\\bHKT\\d*\\b|\\bHKBN\\d*\\b|\\bHGC\\d*\\b|\\bWTT\\d*\\b|\\bCMI\\d*\\b|\\bHK\\d*\\b)([\u4e00-\u9fa5].*|\\d*)"
replace = "ğŸ‡­ğŸ‡° é¦™æ¸¯$2"

[[rename_node]]
match = "^((ã€Œ|\u300c)(ğŸ‡­ğŸ‡°)(ã€|\u300d))(.*)"
replace = "ğŸ‡­ğŸ‡° é¦™æ¸¯$5"

[[rename_node]]
match = "^(ğŸ‡ºğŸ‡¸\\s*)?((?i:\\bUS[A]?\\d*\\b)|((ã€Œ|\\u300c)(ğŸ‡ºğŸ‡¸)(ã€|\\u300d)))\\s*(.*)"
replace = "ğŸ‡ºğŸ‡¸ ç¾å›½$7"

[[rename_node]]
match = "^(ğŸ‡¯ğŸ‡µ\\s*)?((?i:\\bJP[N]?\\d*\\b)|((ã€Œ|\\u300c)(ğŸ‡¯ğŸ‡µ)(ã€|\\u300d)))\\s*(.*)"
replace = "ğŸ‡¯ğŸ‡µ æ—¥æœ¬$7"

[[rename_node]]
match = "^(ğŸ‡¹ğŸ‡¼\\s*)?((?i:\\bTW[N]?\\d*\\b)|((ã€Œ|\\u300c)(ğŸ‡¹ğŸ‡¼)(ã€|\\u300d)))\\s*(.*)"
replace = "ğŸ‡¹ğŸ‡¼ å°æ¹¾$7"

[[rename_node]]
match = "^(ğŸ‡²ğŸ‡´\\s*)?((?i:\\bMO\\d*\\b)|((ã€Œ|\\u300c)(ğŸ‡²ğŸ‡´)(ã€|\\u300d)))\\s*(.*)"
replace = "ğŸ‡²ğŸ‡´ æ¾³é—¨$7"

[[rename_node]]
match = "^(ğŸ‡¸ğŸ‡¬\\s*)?((?i:\\bSG[P]?\\d*\\b)|((ã€Œ|\\u300c)(ğŸ‡¸ğŸ‡¬)(ã€|\\u300d)))\\s*(.*)"
replace = "ğŸ‡¸ğŸ‡¬ æ–°åŠ å¡$7"

[[rename_node]]
match = "^(?i:\\bRU[S]?\\d*\\b)(.*)"
replace = "ä¿„ç½—æ–¯$2"

[[rename_node]]
match = "^(\\bT[U]R\\b)(.*)"
replace = "åœŸè€³å…¶$2"

[[rename_node]]
match = "^(ğŸ‡¬ğŸ‡§\\s*)?((?i:\\bUK\\d*\\b|\\bGB[R]?\\d*\\b)|((ã€Œ|\\u300c)(ğŸ‡¬ğŸ‡§)(ã€|\\u300d)))\\s*(.*)"
replace = "ğŸ‡¬ğŸ‡§ è‹±å›½$7"

[[rename_node]]
match = "^(ğŸ‡°ğŸ‡·\\s*)?((?i:(\\b(?<!North\\s)\\bK(orea|OR|R)\\s?\\d*))|((ã€Œ|\\u300c)(ğŸ‡°ğŸ‡·)(ã€|\\u300d)))\\s*(.*)"
replace = "ğŸ‡°ğŸ‡· éŸ©å›½$8"

[[rename_node]]
match = "^(ğŸ‡«ğŸ‡·\\s*)?((?i:\\bFR[A]?\\d*\\b)|((ã€Œ|\\u300c)(ğŸ‡«ğŸ‡·)(ã€|\\u300d)))\\s*(.*)"
replace = "ğŸ‡«ğŸ‡· æ³•å›½$7"

[[rename_node]]
match = "^(ğŸ‡¨ğŸ‡¦\\s*)?((?i:\\bCA[N]?\\d*\\b)|((ã€Œ|\\u300c)(ğŸ‡¨ğŸ‡¦)(ã€|\\u300d)))\\s*(.*)"
replace = "ğŸ‡¨ğŸ‡¦ åŠ æ‹¿å¤§$7"

[[rename_node]]
match = "^(ğŸ‡¦ğŸ‡º\\s*)?((?i:\\bAU[S]?\\d*\\b)|((ã€Œ|\\u300c)(ğŸ‡¦ğŸ‡º)(ã€|\\u300d)))\\s*(.*)"
replace = "ğŸ‡¦ğŸ‡º æ¾³å¤§åˆ©äºš$7"

[[rename_node]]
match = "^(ğŸ‡¨ğŸ‡³\\s*)?((?i:\\bC[H]?N\\b)|((ã€Œ|\\u300c)(ğŸ‡¨ğŸ‡³)(ã€|\\u300d)))\\s*(.*)"
replace = "ğŸ‡¨ğŸ‡³ ä¸­å›½$7"

[[rename_node]]
match = "^(\\bRO\\d*\\b)(.*)"
replace = "ç½—é©¬å°¼äºš$2"

[[rename_node]]
match = "^(\\bBR\\d*\\b)(.*)"
replace = "å·´è¥¿$2"

[[rename_node]]
match = "^(ğŸ‡ªğŸ‡¸\\s*)?((?i:\\bES[P]?\\d*\\b)|((ã€Œ|\\u300c)(ğŸ‡ªğŸ‡¸)(ã€|\\u300d)))\\s*(.*)"
replace = "ğŸ‡ªğŸ‡¸ è¥¿ç­ç‰™$7"

[[rename_node]]
match = "ç§»åŠ¨"
replace = "CM"

[[rename_node]]
match = "ç”µä¿¡"
replace = "CT"

[[rename_node]]
match = "è”é€š"
replace = "CU"

[[rename_node]]
match = "æ·±æ¸¯ä¸“çº¿"
replace = "æ·±æ¸¯"

[[rename_node]]
match = "(è½¬)"
replace = "â–·"

[[rename_node]]
match = "((NF)|(NF\\*)|(BBC)|(abema)|(åŠ¨ç”»ç–¯)|(Netflix)|(å‹•ç•«ç˜‹)|(Hulu)|(\\[æ³¨å†ŒNetflix\\])|(HBO)|(TVB)|(D\\+)|(Disney)|(Yp)|(Youtube)|(Y2B P)|(AI)|(è§£é”æµåª’ä½“)|(åŸç”ŸIP)|(åŸç”Ÿ)|( NF )|( D\\+ )|(æµåª’ä½“)|(-M)|(è§£é”)|(å®¶å®½))"
replace = "[M]"

[[rename_node]]
match = "\\[M\\].*\\[M\\]"
replace = "[M]"

[[rename_node]]
match = "(\\w+|[\u4e00-\u9fa5]+)\\s\\1"
replace = "$1 "

[[rename_node]]
match = "((?:\\p{RI}{2})|[\\x{2600}-\\x{27BF}\\x{1F300}-\\x{1F5FF}\\x{1F600}-\\x{1F64F}\\x{1F680}-\\x{1F6FF}\\x{1F900}-\\x{1F9FF}\\x{1FA70}-\\x{1FAFF}])\\1+"
replace = "$1"

[[rename_node]]
match = "\\[CM\\]|\\[CU\\]|\\[BT\\/PTä¸“ç”¨\\]|\\[è\\]|\\[Beta\\]|\\[ç§»åŠ¨\\]|\\[è”é€š\\]|\\[ç»¼åˆ\\]|\\[å¤‡ç”¨\\]|\\[é˜¿é‡Œäº‘\\]|\\[æµ‹è¯•\\]|\\[v6\\]|é«˜é€Ÿ|100mé™é€Ÿ|CDNåŠ é€Ÿ|Game|PPCW|Sakura"
replace = ""

[[rename_node]]
match = "(.*?)(\\d+(?:\\.\\d+)?)(?:\\s*[xX])(.*)"
replace = "$1[x$2]$3"

[[rename_node]]
match = "(.*?)(?:[\\[ã€]\\s*)?(\\d+(?:\\.\\d+)?)(?:\\s*å€(?:ç‡)?)?å€ç‡(?:\\s*[\\]ã€‘])?(.*)"
replace = "$1$3[x$2]"

[[rename_node]]
match = "(.*?)(?:[\\[ã€]?å€ç‡:?[\\]ã€‘]?\\s*(\\d+(?:\\.\\d+)?)(?:\\s*å€(?:ç‡)?)?|(?:x|X)(\\d+(?:\\.\\d+)?))(.*)"
replace = "$1[x$2$3]$4"

[[rename_node]]
match = "(.*)\\[x(\\d+(?:\\.\\d+)?)\\](.*)"
replace = "$1$3[x$2]"

[[rename_node]]
match = "\\[\\]"
replace = ""
