# short names
[[rename_node]]
match = "(è§£é”|)(\\|)(x.*)(\\|V2ray)"
replace = "$[$3]"

[[rename_node]]
match = "(..|...)(\\d\\d\\d\\d|\\d\\d\\d)(\\|)(Azure|HKT|CN2GIA)"
replace = "$1$4$2"

[[rename_node]]
match = "^CordCloud - "
replace = ""

[[rename_node]]
match = "(æ ‡å‡†)|(æ ‡å‡†çº¿è·¯)|(çº¿è·¯)|(ä¸­è½¬)|(ç›´è¿)|(80ç«¯å£)|(V\\d-)|(IEPLä¸“çº¿ )|(IPV6)|((æµ·å¤–\\|æ–°ç–†ä¸“ç”¨))|((\u6d77\u5916\\|\u65b0\u7586\u4e13\u7528))"
replace = ""

[[rename_node]]
match = "(.*)( )(.*\\d)( \\| )(.*)"
replace = "$1$3$5"

[[rename_node]]
match = "(.*)(\\b\\d.*\\d\\b)(é™æ€è§£é”|åŠ¨æ€è§£é”|åŸç”Ÿè§£é”|è§£é”|åŠ¨æ€åŸç”Ÿ|é™æ€åŸç”Ÿ|åŸç”Ÿ)"
replace = "$1$2[M]"

[[rename_node]]
match = "(.*)(\\d.*\\d)(\\|[\\w].*\\d)"
replace = "$1$2"

[[rename_node]]
match = "(.*)(NO)(.?\\d?\\d?\\d)$"
replace = "$1 $3"

# [[rename_node]]
# match = "(ã€Œ|\u300c)(\\p{RI}\\p{RI})(ã€|\u300d)"
# replace = "$2 "

[[rename_node]]
match = "((CN\\dâ€¢)|^)(â“ª|â¶|â·|â¸|â»)(TJ\\.|gR\\.|V2\\.|H2\\.|SS\\.)"
replace = ""

[[rename_node]]
match = "(å•†å®½)|(\\dç»„)|(--)|(â—†)"
replace = ""

[[rename_node]]
match = "^(.*)(?i:\\bHK[G]?\\d*\\b|Hong.*?Kong|\\bHKT\\d*\\b|\\bHKBN\\d*\\b|\\bHGC\\d*\\b|\\bWTT\\d*\\b|\\bCMI\\d*\\b|\\bHK\\d*\\b)([\u4e00-\u9fa5].*|\\d*)"
replace = "é¦™æ¸¯ $2"

[[rename_node]]
match = "^((ã€Œ|\u300c)(ğŸ‡­ğŸ‡°)(ã€|\u300d))(.*)"
replace = "é¦™æ¸¯ $5"

[[rename_node]]
match = "^((?i:\\bUS[A]?\\d*\\b)|((ã€Œ|\u300c)(ğŸ‡ºğŸ‡¸)(ã€|\u300d)))(.*)"
replace = "ç¾å›½ $6"

[[rename_node]]
match = "^((?i:\\bJP[N]?\\d*\\b)|((ã€Œ|\u300c)(ğŸ‡¯ğŸ‡µ)(ã€|\u300d)))(.*)"
replace = "æ—¥æœ¬ $6"

[[rename_node]]
match = "^((?i:\\bTW[N]?\\d*\\b)|((ã€Œ|\u300c)(ğŸ‡¹ğŸ‡¼)(ã€|\u300d)))(.*)"
replace = "å°æ¹¾ $6"

[[rename_node]]
match = "^((?i:\\bMO\\d*\\b)|((ã€Œ|\u300c)(ğŸ‡²ğŸ‡´)(ã€|\u300d)))(.*)"
replace = "æ¾³é—¨ $6"

[[rename_node]]
match = "^((?i:\\bSG[P]?\\d*\\b)|((ã€Œ|\u300c)(ğŸ‡¸ğŸ‡¬)(ã€|\u300d)))(.*)"
replace = "æ–°åŠ å¡ $6"

[[rename_node]]
match = "^(?i:\\bRU[S]?\\d*\\b)(.*)"
replace = "ä¿„ç½—æ–¯ $2"

[[rename_node]]
match = "^(\\bT[U]R\\b)(.*)"
replace = "åœŸè€³å…¶ $2"

[[rename_node]]
match = "^((?i:\\bUK\\d*\\b|\\bGB[R]?\\d*\\b)|((ã€Œ|\u300c)(ğŸ‡¬ğŸ‡§)(ã€|\u300d)))(.*)"
replace = "è‹±å›½ $6"

[[rename_node]]
match = "^((?i:(?<!North\\s)(\\bK[O]?R\\d*\\b))|((ã€Œ|\u300c)(ğŸ‡°ğŸ‡·)(ã€|\u300d)))(.*)"
replace = "éŸ©å›½ $7"

[[rename_node]]
match = "^((?i:\\bFR[A]?\\d*\\b)|((ã€Œ|\u300c)(ğŸ‡«ğŸ‡·)(ã€|\u300d)))(.*)"
replace = "æ³•å›½ $6"

[[rename_node]]
match = "^((?i:\\bCA[N]?\\d*\\b)|((ã€Œ|\u300c)(ğŸ‡¨ğŸ‡¦)(ã€|\u300d)))(.*)"
replace = "åŠ æ‹¿å¤§ $6"

[[rename_node]]
match = "^((?i:\\bAU[S]?\\d*\\b)|((ã€Œ|\u300c)(ğŸ‡¦ğŸ‡º)(ã€|\u300d)))(.*)"
replace = "æ¾³å¤§åˆ©äºš $6"

[[rename_node]]
match = "^((?i:\\bC[H]?N\\b)|((ã€Œ|\u300c)(ğŸ‡¨ğŸ‡³)(ã€|\u300d)))(.*)"
replace = "ä¸­å›½ $6"

[[rename_node]]
match = "^(\\bRO\\d*\\b)(.*)"
replace = "ç½—é©¬å°¼äºš $2"

[[rename_node]]
match = "^(\\bBR\\d*\\b)(.*)"
replace = "å·´è¥¿ $2"

[[rename_node]]
match = "^((?i:\\bES[P]?\\d*\\b)|((ã€Œ|\u300c)(ğŸ‡ªğŸ‡¸)(ã€|\u300d)))(.*)"
replace = "è¥¿ç­ç‰™ $6"

[[rename_node]]
match = "ç§»åŠ¨"
replace = "CM"

[[rename_node]]
match = "ç”µä¿¡"
replace = "CT"

[[rename_node]]
match = "è”é€š"
replace = "CU"

[[rename_node]]
match = "æ·±æ¸¯ä¸“çº¿"
replace = "æ·±æ¸¯"

[[rename_node]]
match = "(è½¬)"
replace = "â–·"

[[rename_node]]
match = "((\\|NF)|(\\|NF\\*)|(\\|BBC)|(\\|abema)|(\\|åŠ¨ç”»ç–¯)|(\\|Netflix)|(\\|å‹•ç•«ç˜‹)|(\\|Hulu)|(\\|\\[æ³¨å†ŒNetflix\\])|(\\|HBO)|(\\|TVB)|(\\|D\\+)|(\\|Yp)|(\\|Y2B P)|(\\|AI)|(è§£é”æµåª’ä½“)|(åŸç”ŸIP)|(åŸç”Ÿ)|(\\| NF )|(\\| D\\+ )|(æµåª’ä½“)|(-M)|(è§£é”))"
replace = "[M]"

[[rename_node]]
match = "\\[M\\].*\\[M\\]"
replace = "[M]"

[[rename_node]]
match = "(\\w+|[\u4e00-\u9fa5]+)\\s\\1"
replace = "$1 "

[[rename_node]]
match = "\\[CM\\]|\\[CU\\]|\\[BT\\/PTä¸“ç”¨\\]|\\[è\\]|\\[Beta\\]|\\[ç§»åŠ¨\\]|\\[è”é€š\\]|\\[ç»¼åˆ\\]|\\[å¤‡ç”¨\\]|\\[é˜¿é‡Œäº‘\\]|\\[æµ‹è¯•\\]|\\[v6\\]|é«˜é€Ÿ|100mé™é€Ÿ|CDNåŠ é€Ÿ|Game|PPCW|Sakura"
replace = ""

# [[rename_node]]
# match = "(?!<=[\\]|\\)])$"
# replace = "[x1]"

[[rename_node]]
match = "(x|X)(\\d*.?\\d*\\d)"
replace = "[x$2]"

[[rename_node]]
match = "(.*)(\\[)(å€ç‡:)(.*\\d)(\\])"
replace = "$1[x$4]"

[[rename_node]]
match = "(\\[x.*\\d\\])(.*)"
replace = "$2$1"

[[rename_node]]
match = "(.*)( )(.*\\d)(å€ç‡)"
replace = "$1[x$3]"

[[rename_node]]
match = "(.*)(\\|)(x.*\\d)(å€ç‡)"
replace = "$1[$3]"

[[rename_node]]
match = "(.*)( )(x.*\\d)"
replace = "$1[$3]"

[[rename_node]]
match = "\\[\\]"
replace = ""

[[rename_node]]
match = "\\(?((x|X)?(\\d+)(\\.?\\d+)?)((\\s?å€ç‡?)|(x|X))\\)?"
replace = "[x$1]"
