[[rulesets]]
group = "ğŸ¥¥ DNS Improvement"
ruleset = "https://raw.githubusercontent.com/LM-Firefly/Rules/master/Special/DNS.list"
type = "surge-ruleset"
interval = 3600

[[rulesets]]
group = "â˜ ï¸ è½¯ä»¶éªŒè¯"
ruleset = "https://raw.githubusercontent.com/LM-Firefly/Rules/master/Special/App-Activation.list"
type = "surge-ruleset"
interval = 3600

# [[rulesets]]
# group = "â›”ï¸ å¹¿å‘ŠæœåŠ¡"
# ruleset = "https://raw.githubusercontent.com/LM-Firefly/Rules/master/Adblock/Adblock.list"
# type = "surge-ruleset"
# interval = 3600

[[rulesets]]
group = "â° æ—¶é—´æ ¡å‡†"
ruleset = "https://raw.githubusercontent.com/LM-Firefly/Rules/master/Special/NTP-Service.list"
type = "surge-ruleset"
interval = 3600

[[rulesets]]
group = "ğŸ è‹¹æœæœåŠ¡"
ruleset = "https://raw.githubusercontent.com/LM-Firefly/Rules/master/Apple.list"
type = "surge-ruleset"
interval = 3600

[[rulesets]]
group = "ğŸ“º å“”å“©å“”å“©"
ruleset = "https://raw.githubusercontent.com/LM-Firefly/Rules/master/Global-Services/BiliBiliHMT.list"
type = "surge-ruleset"
interval = 3600

[[rulesets]]
group = "ğŸ“º å“”å“©å“”å“©"
ruleset = "https://raw.githubusercontent.com/LM-Firefly/Rules/master/Domestic-Services/BiliBili.list"
type = "surge-ruleset"
interval = 3600

[[rulesets]]
group = "ğŸ™ˆ è°·æ­ŒæœåŠ¡"
ruleset = "https://raw.githubusercontent.com/LM-Firefly/Rules/master/PROXY/Google.list"
type = "surge-ruleset"
interval = 3600

[[rulesets]]
group = "ğŸ¥ æ”¿åºœç½‘ç«™"
ruleset = "https://raw.githubusercontent.com/LM-Firefly/Rules/master/Special/Government-CN.list"
type = "surge-ruleset"
interval = 3600

[[rulesets]]
group = "ğŸ¥ çˆ±å¥‡è‰º"
ruleset = "https://raw.githubusercontent.com/LM-Firefly/Rules/master/Global-Services/iQIYI-Intl.list"
type = "surge-ruleset"
interval = 3600

[[rulesets]]
group = "ğŸ¥ çˆ±å¥‡è‰º"
ruleset = "https://raw.githubusercontent.com/LM-Firefly/Rules/master/Domestic-Services/iQIYI.list"
type = "surge-ruleset"
interval = 3600

[[rulesets]]
group = "ğŸ» LineTV"
ruleset = "https://raw.githubusercontent.com/LM-Firefly/Rules/master/Global-Services/LineTV.list"
type = "surge-ruleset"
interval = 3600

[[rulesets]]
group = "ğŸ¼ å¾®è½¯æœåŠ¡"
ruleset = "https://raw.githubusercontent.com/LM-Firefly/Rules/master/Microsoft.list"
type = "surge-ruleset"
interval = 3600

[[rulesets]]
group = "ğŸ· ç½‘æ˜“éŸ³ä¹"
ruleset = "https://raw.githubusercontent.com/LM-Firefly/Rules/master/Domestic-Services/NeteaseMusic.list"
type = "surge-ruleset"
interval = 3600

[[rulesets]]
group = "ğŸ¥ å¥ˆé£å½±è§†"
ruleset = "https://raw.githubusercontent.com/LM-Firefly/Rules/master/Global-Services/Netflix.list"
type = "surge-ruleset"
interval = 3600

[[rulesets]]
group = "ğŸ¤– OpenAI"
ruleset = "https://raw.githubusercontent.com/LM-Firefly/Rules/master/PROXY/OpenAI.list"
type = "surge-ruleset"
interval = 3600

[[rulesets]]
group = "ğŸ“² ç”µæŠ¥æ¶ˆæ¯"
ruleset = "https://raw.githubusercontent.com/LM-Firefly/Rules/master/PROXY/Telegram.list"
type = "surge-ruleset"
interval = 3600

[[rulesets]]
group = "ğŸ¬ æ¨è¶£å½±éŸ³"
ruleset = "https://raw.githubusercontent.com/LM-Firefly/Rules/master/PROXY/Twitch.list"
type = "surge-ruleset"
interval = 3600

[[rulesets]]
group = "ğŸ“¡ è§†é¢‘è§£æ"
ruleset = "https://raw.githubusercontent.com/LM-Firefly/Rules/master/Special/Video-Crack.list"
type = "surge-ruleset"
interval = 3600

[[rulesets]]
group = "ğŸ’Š å°ç±³æœåŠ¡"
ruleset = "https://raw.githubusercontent.com/LM-Firefly/Rules/master/Domestic-Services/Xiaomi.list"
type = "surge-ruleset"
interval = 3600

[[rulesets]]
group = "ğŸš¦ DMCA Sensitive"
ruleset = "https://raw.githubusercontent.com/LM-Firefly/Rules/master/Special/DMCA-Sensitive.list"
type = "surge-ruleset"
interval = 3600

[[rulesets]]
group = "ğŸ¯ ç›´è¿æœåŠ¡"
ruleset = "https://raw.githubusercontent.com/LM-Firefly/Rules/master/Special/TeamViewer-CIDR.list"
type = "surge-ruleset"
interval = 3600

[[rulesets]]
group = "ğŸ•¸ï¸ å±€åŸŸç½‘æœåŠ¡"
ruleset = "https://raw.githubusercontent.com/LM-Firefly/Rules/master/Special/LAN-Special-Apps.list"
type = "surge-ruleset"
interval = 3600

[[rulesets]]
group = "ğŸ® æ¸¸æˆæœåŠ¡"
ruleset = "https://raw.githubusercontent.com/LM-Firefly/Rules/master/Game.list"
type = "surge-ruleset"
interval = 3600

[[rulesets]]
group = "ğŸŒ å›½å¤–åª’ä½“"
ruleset = "https://raw.githubusercontent.com/LM-Firefly/Rules/master/GlobalMedia.list"
type = "surge-ruleset"
interval = 3600

[[rulesets]]
group = "ğŸ– é»˜è®¤ä»£ç†"
ruleset = "https://raw.githubusercontent.com/LM-Firefly/Rules/master/PROXY.list"
type = "surge-ruleset"
interval = 3600

[[rulesets]]
group = "ğŸ± é˜¿é‡Œå·´å·´"
ruleset = "https://raw.githubusercontent.com/LM-Firefly/Rules/master/Domestic-Services/Alibaba.list"
type = "surge-ruleset"
interval = 3600

[[rulesets]]
group = "ğŸŒ å¤§é™†æœåŠ¡"
ruleset = "https://raw.githubusercontent.com/LM-Firefly/Rules/master/Domestic.list"
type = "surge-ruleset"
interval = 3600

[[rulesets]]
group = "ğŸŒ å¤§é™†æœåŠ¡"
ruleset = "https://raw.githubusercontent.com/LM-Firefly/Rules/master/CCC-CN.list"
type = "surge-ruleset"
interval = 3600

[[rulesets]]
group = "ğŸ– é»˜è®¤ä»£ç†"
ruleset = "https://raw.githubusercontent.com/LM-Firefly/Rules/master/CCC-Global.list"
type = "surge-ruleset"
interval = 3600

[[rulesets]]
group = "ğŸš€ SpeedTest"
ruleset = "https://raw.githubusercontent.com/LM-Firefly/Rules/master/SpeedTest.list"
type = "surge-ruleset"
interval = 3600

[[rulesets]]
group = "ğŸ¯ ç›´è¿æœåŠ¡"
ruleset = "https://raw.githubusercontent.com/LM-Firefly/Rules/master/Special/Local-LAN.list"
type = "surge-ruleset"
interval = 3600

[[rulesets]]
group = "ğŸŒ å¤§é™†æœåŠ¡"
ruleset = "https://raw.githubusercontent.com/LM-Firefly/Rules/master/CN-IP.list"
type = "surge-ruleset"
interval = 3600

[[rulesets]]
group = "ğŸŒ å¤§é™†æœåŠ¡"
ruleset = "[]GEOIP,CN"

[[rulesets]]
group = "ğŸš§ ç»ˆæœ«ç­–ç•¥"
ruleset = "[]MATCH"
